version: '2'

volumes:
  mongo_data: {}

services:
  node:
    restart: always
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    # command: bash
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongo:27017/watch-football"
    volumes:
      - /home/app/watch-football-backend/uploads
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    # tty: true
  frontend:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    ports:
      - '8080:8080'
    command: serve -s -p 8080 build
  mongo:
    restart: always
    image: mongo:3
    command: mongod --smallfiles
    volumes:
      - mongo_data:/data/db
  nginx:
    restart: always
    build: ./compose/nginx
    volumes_from:
      - node
    depends_on:
      - node
    ports:
      - "80:80"